#!/usr/bin/env node
/**
 * Build script for Vercel deployment
 * Generates config.js from environment variables
 *
 * In Vercel dashboard:
 * 1. Go to Project Settings > Environment Variables
 * 2. Add OPENROUTER_API_KEY with your API key
 * 3. Deploy - this script will create config.js automatically
 */

const fs = require('fs');
const path = require('path');

console.log('=== MRI-Crohn Atlas Build Script ===');
console.log('Working directory:', process.cwd());

const apiKey = process.env.OPENROUTER_API_KEY;

if (!apiKey) {
    console.warn('WARNING: OPENROUTER_API_KEY environment variable not set.');
    console.warn('Parser will show "API key not configured" error to users.');
    console.warn('To fix: Add OPENROUTER_API_KEY in Vercel Project Settings > Environment Variables');
    // Still create an empty config so the file exists (avoids 404)
} else {
    console.log('API key found: sk-or-....' + apiKey.slice(-4));
}

const configContent = `/**
 * MRI-Crohn Atlas Configuration
 * Auto-generated by build script - DO NOT EDIT
 */
const CONFIG = {
    OPENROUTER_API_KEY: '${apiKey || ''}'
};

if (typeof window !== 'undefined') {
    window.CONFIG = CONFIG;
}
`;

const outputPath = path.join(__dirname, '..', 'src', 'web', 'config.js');

try {
    // Ensure the directory exists
    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
        console.log('Creating directory:', outputDir);
        fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, configContent);
    console.log('SUCCESS: config.js generated at:', outputPath);

    // Verify the file was created
    if (fs.existsSync(outputPath)) {
        const stats = fs.statSync(outputPath);
        console.log('File size:', stats.size, 'bytes');
    }
} catch (error) {
    console.error('FAILED to write config.js:', error.message);
    console.error('Full error:', error);
    process.exit(1);
}

console.log('=== Build Complete ===');
